### PR TITLE
Hotfix #25 malfored field filter

### LINKED ISSUE #25: Malformed field filter crash

### PR DESCRIPTION
**Pull request by VilleKoivukangas**
fixes #25

### CODE REVIEW

File: src/main/java/fi/metatavu/metaform/server/metaforms/FieldController.java [hunk 1]
```diff
@@ -57,11 +59,23 @@ public FieldFilters parseFilters(Metaform metaform, List<String> filterList) {
       return null;
     }
     
-    List<FieldFilter> filters = filterList.stream()
+    List<String> filterListCombined = new ArrayList<>(filterList.size());
+    
+    filterList.stream()
       .filter(StringUtils::isNoneEmpty)
+      .forEach((filter) -> {
```
Comment (sonarq) [inline src/main/java/fi/metatavu/metaform/server/metaforms/FieldController.java]: Code Smell Code Smell: Remove the parentheses around the "filter" parameter ([squid:S1611](https://sonarcloud.io/organizations/metatavu-oy/rules#rule_key=squid%3AS1611))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fi.metatavu.metaform-api%3Ametaform-api&pullRequest=26&issues=AWPKM9Kx4427HkKVgpDj&open=AWPKM9Kx4427HkKVgpDj)

[ISSUE_KEY]: AWPKM9Kx4427HkKVgpDj

Comment (sonarq) [inline src/main/java/fi/metatavu/metaform/server/metaforms/FieldController.java]: Code Smell Code Smell: Remove useless curly braces around statement ([squid:S1602](https://sonarcloud.io/organizations/metatavu-oy/rules#rule_key=squid%3AS1602))

[See it in SonarCloud](https://sonarcloud.io/project/issues?id=fi.metatavu.metaform-api%3Ametaform-api&pullRequest=26&issues=AWPKM9Kx4427HkKVgpDi&open=AWPKM9Kx4427HkKVgpDi)

[ISSUE_KEY]: AWPKM9Kx4427HkKVgpDi
